name: run-tests

on:
  pull_request:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: install requirements
        run: pip install -r requirements.txt
        shell: bash

      - name: run test
        run: python -m unittest
        shell: bash
